FROM tiangolo/uwsgi-nginx-flask:python3.8
ENV APP=/app

RUN apt-get update && apt-get install -y python3-dev gcc  libc-dev libsasl2-dev python-dev libldap2-dev libssl-dev

# Set the working directory to /app
WORKDIR $APP

# Copy the current directory contents into the container at /app 
ADD . $APP

RUN python3 -m venv $APP/env
ENV PATH "${APP}/env/bin:${APP}:${PATH}"

# Install the dependencies
RUN pip install -r requirements.txt

ENV STATIC_PATH $APP/memos/static
